// <auto-generated />
namespace OnlineTheater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial4));
        
        string IMigrationMetadata.Id
        {
            get { return "202012242152009_initial4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
